const wordList = {
    easy: [
        { word: "sun", hint: "The star around which the Earth and other planets orbit." },
        { word: "happy", hint: "Feeling or showing pleasure, contentment, or joy." },
        { word: "bird", hint: "A warm-blooded, feathered vertebrate with wings, typically able to fly." },
        { word: "play", hint: "Engage in activity for enjoyment and recreation." },
        { word: "lamp", hint: "A device for giving light, typically consisting of a bulb and shade." },
        { word: "beach", hint: "A shore of a body of water, especially when sandy or pebbly." },
        { word: "cake", hint: "A sweet baked food item typically made from flour, sugar, and eggs." },
        { word: "star", hint: "A luminous celestial body consisting of a mass of gas held together by gravity." },
        { word: "moon", hint: "The natural satellite of the Earth, visible by reflected sunlight." },
        { word: "color", hint: "The property possessed by an object of producing different sensations on the eye." },
    ],
    normal: [
        { word: "element", hint: "Defined by a start tag, some content, and an end tag." },
        { word: "flower", hint: "The reproductive structure found in plants, often colorful and fragrant." },
        { word: "friend", hint: "A person with whom one has a bond of mutual affection and support." },
        { word: "music", hint: "An art form and cultural activity consisting of organized sound elements." },
        { word: "tree", hint: "A woody perennial plant, typically with a single main stem and branches." },
        { word: "cloud", hint: "A visible mass of water droplets or ice crystals suspended in the atmosphere." },
        { word: "computer", hint: "An electronic device for storing and processing data." },
        { word: "ocean", hint: "A vast expanse of saltwater that covers most of the Earth's surface." },
        { word: "journey", hint: "An act of traveling from one place to another." },
        { word: "diamond", hint: "A precious stone consisting of a clear and colorless crystalline form of pure carbon." },
    ],
    hard: [
        { word: "unpredictable", hint: "Not able to be foreseen or known beforehand; uncertain." },
        { word: "architecture", hint: "The art and science of designing and constructing buildings." },
        { word: "kaleidoscope", hint: "A constantly changing pattern or sequence of elements." },
        { word: "quasar", hint: "An extremely bright and distant point-like object in the universe." },
        { word: "xenophobia", hint: "Dislike or prejudice against people from other countries." },
        { word: "philanthropy", hint: "The desire to promote the welfare of others, expressed by the donation of money, resources, or time." },
        { word: "onomatopoeia", hint: "The formation of a word from a sound associated with what is named." },
        { word: "serendipity", hint: "The occurrence and development of events by chance in a happy or beneficial way." },
        { word: "ubiquitous", hint: "Present, appearing, or found everywhere." },
        { word: "sesquipedalian", hint: "A very long word or a person who uses long words." },
    ],
};

